name: Test-Subunit
abstract: Parse and generate Subunit streams
author:
    - Jelmer Vernooij <jelmer@samba.org>
license: apachev2
installdirs:  site
homepage: https://github.com/jelmer/subunit-perl
bugtracker: https://github.com/jelmer/subunit-perl/issues
meta-spec:
    version: 1.3
    url: http://module-build.sourceforge.net/META-spec-v1.3.html
