#!/usr/bin/perl
# Run a Perl test suite and emit results in the subunit protocol.
# Copyright (C) 2026 Jelmer Vernooij <jelmer@samba.org>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

use strict;
use warnings;
use Getopt::Long qw(:config require_order pass_through);

my $prove = $ENV{PROVE} || 'prove';
my $tap2subunit = $ENV{TAP2SUBUNIT} || 'tap2subunit';
my $help = 0;

GetOptions(
    'prove=s'       => \$prove,
    'tap2subunit=s' => \$tap2subunit,
    'help|h'        => \$help,
) or usage(2);

usage(0) if $help;

sub usage {
    my ($rc) = @_;
    my $fh = $rc ? \*STDERR : \*STDOUT;
    print $fh <<"EOF";
Usage: $0 [options] [-- prove-args...] [test files or dirs]

Run a Perl test suite via prove(1) and emit results on stdout in the
subunit protocol by piping TAP through tap2subunit(1).

Options:
  --prove=PATH        Path to the prove binary (default: prove, or \$PROVE)
  --tap2subunit=PATH  Path to tap2subunit (default: tap2subunit, or \$TAP2SUBUNIT)
  -h, --help          Show this help

Any arguments after -- (or unrecognised options) are passed to prove.
Without arguments, prove defaults to running t/*.t.

Examples:
  $0 t/
  $0 -- --jobs 4 t/some_test.t
EOF
    exit $rc;
}

shift @ARGV if @ARGV && $ARGV[0] eq '--';

# --verbose makes prove emit TAP on stdout (otherwise only a summary);
# --merge folds each test's stderr into the same stream so diagnostics survive.
my @prove_args = ('--merge', '--verbose', @ARGV);

pipe(my $rh, my $wh) or die "pipe: $!";

my $prove_pid = fork();
die "fork: $!" unless defined $prove_pid;
if ($prove_pid == 0) {
    close $rh;
    open(STDOUT, '>&', $wh) or die "dup STDOUT: $!";
    close $wh;
    exec($prove, @prove_args) or die "exec $prove: $!";
}
close $wh;

my $t2s_pid = fork();
die "fork: $!" unless defined $t2s_pid;
if ($t2s_pid == 0) {
    open(STDIN, '<&', $rh) or die "dup STDIN: $!";
    close $rh;
    exec($tap2subunit) or die "exec $tap2subunit: $!";
}
close $rh;

waitpid($prove_pid, 0);
my $prove_status = $?;
waitpid($t2s_pid, 0);
my $t2s_status = $?;

# Prefer to report a failure from tap2subunit, but otherwise surface
# the prove exit status (non-zero when tests failed).
if ($t2s_status != 0) {
    exit($t2s_status >> 8 || 1);
}
exit($prove_status >> 8);
